---
title: 'Wildfire Project: COVID-19 Plots'
author: "Blake Bullwinkel"
date: "12/1/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
library(ggplot2)
```

```{r}
# Read in the COVID-19 data
covid_data = read.csv('covid-counties.csv')

# Filter state for California and county for San Francisco
ca_covid_data = covid_data[(covid_data$state=='California'),]
sanfran_covid_data = ca_covid_data[(ca_covid_data$county=='San Francisco'),]

# Filter state for Washington and county for Spokane
wa_covid_data = covid_data[(covid_data$state=='Washington'),]
spokane_covid_data = wa_covid_data[(wa_covid_data$county=='Spokane'),]

# Filter state for Oregon and county for Multnomah
or_covid_data = covid_data[(covid_data$state=='Oregon'),]
portland_covid_data = or_covid_data[(or_covid_data$county=='Multnomah'),]

# Convert date fields to POSIXct objects
sanfran_covid_data$date = ymd(sanfran_covid_data$date)
spokane_covid_data$date = ymd(spokane_covid_data$date)
portland_covid_data$date = ymd(portland_covid_data$date)
```

```{r}
# Calculate the daily new COVID cases in San Francisco by county
ca_covid_data = transform(ca_covid_data, new_cases = ave(cases, county, FUN=function(x) x - c(0, head(x, -1))))

# Calculate the daily new COVID cases in Washington by county
wa_covid_data = transform(wa_covid_data, new_cases = ave(cases, county, FUN=function(x) x - c(0, head(x, -1))))

# Calculate the daily new COVID cases in Oregon by county
or_covid_data = transform(or_covid_data, new_cases = ave(cases, county, FUN=function(x) x - c(0, head(x, -1))))
```

```{r}
# Read in the daily PM2.5 data
ca_pm = read.csv('CA_2020_ad_viz_plotval_data.csv')
wa_pm = read.csv('WA_2020_ad_viz_plotval_data.csv')
or_pm = read.csv('OR_2020_ad_viz_plotval_data.csv')

# Convert date fields to POSIXct objects
ca_pm$Date = mdy(ca_pm$Date)
wa_pm$Date = mdy(wa_pm$Date)
or_pm$Date = mdy(or_pm$Date)

# Filter the PM2.5 data to span the same date range as the COVID data
ca_pm = ca_pm[(ca_pm$Date > '2010-01-25'),]
wa_pm = wa_pm[(wa_pm$Date > '2010-01-21'),]
or_pm = or_pm[(or_pm$Date > '2010-02-28'),]

# Merge the California daily PM2.5 and daily COVID data by county and date
colnames(ca_pm)[18] = 'county'
ca_daily_covid_pm = merge(ca_covid_data, ca_pm, by='county')
ca_daily_covid_pm = ca_daily_covid_pm[ca_daily_covid_pm$Date==ca_daily_covid_pm$date,]
```

```{r}
# Plot daily COVID cases vs daily PM2.5 in California counties
ggplot(data=ca_daily_covid_pm) +
  geom_point(aes(x=Daily.Mean.PM2.5.Concentration, y=new_cases), size=2, color='red') +
  ylab("Daily New COVID-19 Cases") + xlab("Daily PM 2.5") + 
  ggtitle("CA County Daily COVID-19") +
  theme(text=element_text(size=14,  family="Arial Narrow"), 
        panel.border = element_blank(),
        panel.grid.major = element_line(color = "lightgrey"),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"))
```